name: Build & Lint
on:
  workflow_call:


jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "./pyproject.toml"
          prune-cache: true
      
      
      - name: Install dependencies
        run: uv sync --locked --dev
      
      - name: Run ruff check
        run: make lint
      
      - name: Run Type Check
        run: make  type-check 